from typing import Protocol
from uuid import UUID

from orqalis.domain.approval import ApprovalDecision, ApprovalRequest, ControlPolicy


class ApprovalRepository(Protocol):
    def policy(self, run_id: UUID) -> ControlPolicy | None: ...
    def save_policy(self, policy: ControlPolicy) -> None: ...
    def get(self, request_id: UUID) -> ApprovalRequest | None: ...
    def list(self, run_id: UUID) -> tuple[ApprovalRequest, ...]: ...
    def add_request(self, request: ApprovalRequest) -> None: ...
    def add_decision(self, decision: ApprovalDecision) -> None: ...
