from typing import Protocol
from uuid import UUID

from orqalis.domain.artifact import Artifact, Finding
from orqalis.domain.delivery import ChangeReport, FinalValidation, GitDelivery


class DeliveryRepository(Protocol):
    def guardians(self, run_id: UUID) -> tuple[ChangeReport, ...]: ...
    def save_guardian(self, report: ChangeReport) -> None: ...
    def validations(self, run_id: UUID) -> tuple[FinalValidation, ...]: ...
    def save_validation(self, validation: FinalValidation) -> None: ...
    def get(self, run_id: UUID) -> GitDelivery | None: ...
    def save(self, delivery: GitDelivery) -> None: ...
    def artifacts(self, run_id: UUID) -> tuple[Artifact, ...]: ...
    def save_artifact(self, artifact: Artifact) -> None: ...
    def findings(self, run_id: UUID) -> tuple[Finding, ...]: ...
    def save_finding(self, finding: Finding) -> None: ...
