from typing import Protocol
from uuid import UUID

from orqalis.domain.execution import ReviewRecord, RunWorkspace, ToolInvocation


class ExecutionRepository(Protocol):
    def try_run_lock(self, run_id: UUID) -> bool: ...
    def workspace(self, run_id: UUID) -> RunWorkspace | None: ...
    def save_workspace(self, workspace: RunWorkspace) -> None: ...
    def tool(self, invocation_id: UUID) -> ToolInvocation | None: ...
    def save_tool(self, invocation: ToolInvocation) -> None: ...
    def tools(self, run_id: UUID) -> tuple[ToolInvocation, ...]: ...
    def save_review(self, review: ReviewRecord) -> None: ...
    def reviews(self, run_id: UUID) -> tuple[ReviewRecord, ...]: ...
