from typing import Protocol
from uuid import UUID

from orqalis.domain.acceptance import AcceptanceCriterion, GoalContract
from orqalis.domain.artifact import Evidence
from orqalis.domain.run import Run


class RunRepository(Protocol):
    def add(self, run: Run) -> None: ...
    def get(self, run_id: UUID, for_update: bool = False) -> Run | None: ...
    def list(self, project_id: UUID | None = None, limit: int = 100) -> tuple[Run, ...]: ...
    def save(self, run: Run) -> None: ...
    def save_goal(self, contract: GoalContract) -> None: ...
    def set_current_goal(self, run_id: UUID, goal_id: UUID) -> None: ...
    def get_goal(self, goal_id: UUID) -> GoalContract | None: ...
    def get_evidence(self, evidence_id: UUID) -> Evidence | None: ...
    def save_criterion(self, criterion: AcceptanceCriterion) -> None: ...
    def save_evaluation(self, criterion: AcceptanceCriterion, evidence: Evidence) -> None: ...
