from typing import Protocol
from uuid import UUID

from orqalis.domain.agent import ActorSession
from orqalis.domain.plan import TaskPlan
from orqalis.domain.task import Task, TaskExecution
from orqalis.domain.timing import PhaseExecution


class RuntimeRepository(Protocol):
    def add_task(self, task: Task) -> None: ...
    def tasks(self, run_id: UUID) -> tuple[Task, ...]: ...
    def save_plan(self, plan: TaskPlan) -> None: ...
    def get_plan(self, run_id: UUID, version: int) -> TaskPlan | None: ...
    def save_task(self, task: Task) -> None: ...
    def actors(self, run_id: UUID) -> tuple[ActorSession, ...]: ...
    def save_actor(self, actor: ActorSession) -> None: ...
    def executions(self, run_id: UUID) -> tuple[TaskExecution, ...]: ...
    def save_execution(self, execution: TaskExecution) -> None: ...
    def phases(self, run_id: UUID) -> tuple[PhaseExecution, ...]: ...
    def save_phase(self, phase: PhaseExecution) -> None: ...
